apiVersion: serving.knative.dev/v1alpha1
kind: Install
metadata:
  name: example-install
spec:
  config:
    defaults:
      revision-timeout-seconds: "300"
      revision-cpu-request: "400m"
    autoscaler:
      container-concurrency-target-percentage: "1.0"
      container-concurrency-target-default: "100"
      stable-window: "60s"
      panic-window: "6s"
      max-scale-up-rate: "10"
      enable-scale-to-zero: "true"
      tick-interval: "2s"
      scale-to-zero-grace-period: "30s"
    controller:
      registriesSkippingTagResolving: "ko.local,dev.local"
    gc:
      stale-revision-create-delay: "24h"
      stale-revision-timeout: "15h"
      stale-revision-minimum-generations: "1"
      stale-revision-lastpinned-debounce: "5h"
    logging:
      loglevel.controller: "info"
      loglevel.autoscaler: "info"
      loglevel.queueproxy: "info"
      loglevel.webhook: "info"
      loglevel.activator: "info"
