apiVersion: istio.openshift.com/v1alpha3
kind: ControlPlane
metadata:
  name: minimal-istio
spec:
  istio:
    global:
      # use community images
      hub: "maistra"
      tag: 0.10.0
      proxy:
        autoInject: disabled
      useMCP: false
      disablePolicyChecks: false
      omitSidecarInjectorConfigMap: true
    galley:
      enabled: false
    gateways:
      istio-ingressgateway:
        autoscaleEnabled: false
      istio-egressgateway:
        enabled: false
    grafana:
      enabled: false
    mixer:
      enabled: false
      policy:
        enabled: false
      telemetry:
        enabled: false
    pilot:
      autoscaleEnabled: false
      sidecar: false
    prometheus:
      enabled: false
    security:
      enabled: false
    sidecarInjectorWebhook:
      enabled: false
    kiali:
      enabled: false
    tracing:
      enabled: false
