kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: knative-serving-operator
subjects:
- kind: ServiceAccount
  name: knative-serving-operator
roleRef:
  kind: Role
  name: knative-serving-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: knative-serving-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: knative-serving-operator
subjects:
- kind: ServiceAccount
  name: knative-serving-operator
  namespace: default
